{% set name = "frozendict" %}
{% set version = "2.2.1" %}
{% set sha256 = "e762dfca8acf09d2977bb8c8849c7442ca0b3233da52e0af36f0fef08c4d808e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv

    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict
  
  - name: {{ name }}-noarch
    build:
      script: {{ PYTHON }} setup.py py bdist_wheel

    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel

      run:
        - python

    test:
      imports:
        - frozendict

about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict

extra:
  recipe-maintainers:
    - ltalirz
    - Marco-Sulla
